### ISSUE TITLE
connection error using 3.7 or 3.8

### ISSUE THREAD

**Issue by McCroden** [untitled-ai/jupyter_ascending#1]
I tried with python version 3.8.5. This information shown here is using python 3.7.8. Same issue on both version. 

Install instructions were followed. 

command to launch jupyter: `jupyter notebook --port 12517`

`/tmp/jupyter_ascending/log.log`:

```shell
2020-10-07 14:49:55.962 | INFO     | jupyter_ascending.extension:load_ipython_extension:13 - Loading Ipython...
2020-10-07 14:49:55.968 | INFO     | jupyter_ascending.extension:load_ipython_extension:19 - IPYTHON: Loading /home/stuart/code/learn/jupyter/test.synced.ipynb
2020-10-07 14:49:55.968 | INFO     | jupyter_ascending.extension:load_ipython_extension:25 - IPYTHON LOAD: Wed Oct  7 14:49:55 2020: /home/stuart/code/learn/jupyter/test.synced.ipynb
2020-10-07 14:49:55.980 | INFO     | jupyter_ascending.handlers.jupyter_notebook:start_notebook_server_in_thread:75 - IPYTHON: Registering notebook /home/stuart/code/learn/jupyter/test.synced.ipynb
2020-10-07 14:49:56.047 | ERROR    | jupyter_ascending.extension:load_ipython_extension:26 - An error has been caught in function 'load_ipython_extension', process 'MainProcess' (1021300), thread 'MainThread' (139987626424128):
Traceback (most recent call last):
  File "/home/stuart/.pyenv/versions/3.7.8/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
                └ ModuleSpec(name='ipykernel_launcher', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f51687a3110>, origin='...
  File "/home/stuart/.pyenv/versions/3.7.8/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x7f5168796ae0, file "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/ip...
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/ipykernel/ker...
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/traitlets/config/application.py", line 837, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x7f5164aca8c0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x7f51688babd0>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 612, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x7f5164c50c20>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f5164aeb7d0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x7f51688babd0>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x7f51677afb90>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f5164aeb7d0>
  File "/home/stuart/.pyenv/versions/3.7.8/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f51677b1680>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/home/stuart/.pyenv/versions/3.7.8/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f51678019e0>
    └ <Handle IOLoop.add_future.<locals>.<lambda>(<Future finis...0e90>, ...]))>) at /home/stuart/.pyenv/versions/3.7.8/envs/jupyte...
  File "/home/stuart/.pyenv/versions/3.7.8/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle IOLoop.add_future.<locals>.<lambda>(<Future finis...0e90>, ...]))>) at /home/stuart/.pyenv/versions/3.7.8/envs/jupyte...
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle IOLoop.add_future.<locals>.<lambda>(<Future finis...0e90>, ...]))>) at /home/stuart/.pyenv/versions/3.7.8/envs/jupyte...
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle IOLoop.add_future.<locals>.<lambda>(<Future finis...0e90>, ...]))>) at /home/stuart/.pyenv/versions/3.7.8/envs/jupyte...
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/tornado/ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
           │  │    │             │         │       │         └ <Future finished result=(10, 1, <bound method...7f5164aeb290>>, (<zmq.eventloo...x7f5164aebf50>, [<zmq.sugar.fr...x7f5164b209...
           │  │    │             │         │       └ <function Runner.handle_yield.<locals>.inner at 0x7f5161200320>
           │  │    │             │         └ <class 'functools.partial'>
           │  │    │             └ <module 'functools' from '/home/stuart/.pyenv/versions/3.7.8/lib/python3.7/functools.py'>
           │  │    └ <function IOLoop._run_callback at 0x7f5164d62d40>
           │  └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f5164aeb7d0>
           └ <Future finished result=(10, 1, <bound method...7f5164aeb290>>, (<zmq.eventloo...x7f5164aebf50>, [<zmq.sugar.fr...x7f5164b209...
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
          └ functools.partial(<function Runner.handle_yield.<locals>.inner at 0x7f5161200320>, <Future finished result=(10, 1, <bound met...
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/tornado/gen.py", line 787, in inner
    self.run()
    │    └ <function Runner.run at 0x7f5164c5b950>
    └ <tornado.gen.Runner object at 0x7f51611ec150>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
              │    │   │    └ (10, 1, <bound method Kernel.dispatch_shell of <ipykernel.ipkernel.IPythonKernel object at 0x7f5164aeb290>>, (<zmq.eventloop....
              │    │   └ <method 'send' of 'generator' objects>
              │    └ <generator object Kernel.process_one at 0x7f5164aa8bd0>
              └ <tornado.gen.Runner object at 0x7f51611ec150>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
          │   │            │         └ (<zmq.eventloop.zmqstream.ZMQStream object at 0x7f5164aebf50>, [<zmq.sugar.frame.Frame object at 0x7f5164b20950>, <zmq.sugar....
          │   │            └ <bound method Kernel.dispatch_shell of <ipykernel.ipkernel.IPythonKernel object at 0x7f5164aeb290>>
          │   └ <function maybe_future at 0x7f5164c5b560>
          └ <module 'tornado.gen' from '/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/tornado/gen.py'>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
                   └ <generator object Kernel.dispatch_shell at 0x7f5164aa8b50>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
          │   │            │       │       │       └ {'header': {'msg_id': '558ea71dc65a4c50b456b00e1e9f417b', 'username': 'username', 'session': '612ed259e636471da3e16a63a4a233e...
          │   │            │       │       └ [b'612ed259e636471da3e16a63a4a233ed']
          │   │            │       └ <zmq.eventloop.zmqstream.ZMQStream object at 0x7f5164aebf50>
          │   │            └ <bound method Kernel.execute_request of <ipykernel.ipkernel.IPythonKernel object at 0x7f5164aeb290>>
          │   └ <function maybe_future at 0x7f5164c5b560>
          └ <module 'tornado.gen' from '/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/tornado/gen.py'>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
                   └ <generator object Kernel.execute_request at 0x7f5164aa8cd0>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 545, in execute_request
    user_expressions, allow_stdin,
    │                 └ False
    └ {}
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
                   └ <generator object IPythonKernel.do_execute at 0x7f5164aa8d50>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 306, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
          │     │        │                   │                     └ True
          │     │        │                   └ False
          │     │        └ '%load_ext jupyter_ascending'
          │     └ <function ZMQInteractiveShell.run_cell at 0x7f5164ab09e0>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7f5164aeb050>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
                 │                    │               │       └ {'store_history': False, 'silent': True}
                 │                    │               └ ('%load_ext jupyter_ascending',)
                 │                    └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7f5164aeb050>
                 └ <class 'ipykernel.zmqshell.ZMQInteractiveShell'>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2877, in run_cell
    raw_cell, store_history, silent, shell_futures)
    │         │              │       └ True
    │         │              └ True
    │         └ False
    └ '%load_ext jupyter_ascending'
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2922, in _run_cell
    return runner(coro)
           │      └ <coroutine object InteractiveShell.run_cell_async at 0x7f51612008c0>
           └ <function _pseudo_sync_runner at 0x7f51678ccb90>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x7f51612008c0>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3146, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
                  │                       │                └ <ExecutionResult object at 7f5164a6f1d0, execution_count=None error_before_exec=None error_in_exec=None info=<ExecutionInfo o...
                  │                       └ <IPython.core.compilerop.CachingCompiler object at 0x7f5164c3ea90>
                  └ 'none'
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3337, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
              │    │        │     │               └ False
              │    │        │     └ <ExecutionResult object at 7f5164a6f1d0, execution_count=None error_before_exec=None error_in_exec=None info=<ExecutionInfo o...
              │    │        └ <code object <module> at 0x7f5161200ae0, file "<ipython-input-1-5c9708314b02>", line 1>
              │    └ <function InteractiveShell.run_code at 0x7f51678e45f0>
              └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7f5164aeb050>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ {'__name__': '__main__', '__doc__': 'Automatically created module for IPython interactive environment', '__package__': None, ...
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7f5164aeb050>
         │         │    └ <property object at 0x7f51678d1a70>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7f5164aeb050>
         └ <code object <module> at 0x7f5161200ae0, file "<ipython-input-1-5c9708314b02>", line 1>
  File "<ipython-input-1-5c9708314b02>", line 1, in <module>
    get_ipython().run_line_magic('load_ext', 'jupyter_ascending')
    └ <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7f5164aeb050>>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2326, in run_line_magic
    result = fn(*args, **kwargs)
             │   │       └ {}
             │   └ ['jupyter_ascending']
             └ <bound method ExtensionMagics.load_ext of <IPython.core.magics.extension.ExtensionMagics object at 0x7f5161a59190>>
  File "<decorator-gen-57>", line 2, in load_ext
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
                  │   │    │  │  │    └ {}
                  │   │    │  │  └ (<IPython.core.magics.extension.ExtensionMagics object at 0x7f5161a59190>, 'jupyter_ascending')
                  │   │    │  └ <function ExtensionMagics.load_ext at 0x7f5166c017a0>
                  │   │    └ {}
                  │   └ (<IPython.core.magics.extension.ExtensionMagics object at 0x7f5161a59190>, 'jupyter_ascending')
                  └ <function ExtensionMagics.load_ext at 0x7f5166c017a0>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/IPython/core/magics/extension.py", line 33, in load_ext
    res = self.shell.extension_manager.load_extension(module_str)
          │    │     │                                └ 'jupyter_ascending'
          │    │     └ <traitlets.traitlets.Instance object at 0x7f51678dd290>
          │    └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7f5164aeb050>
          └ <IPython.core.magics.extension.ExtensionMagics object at 0x7f5161a59190>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/IPython/core/extensions.py", line 87, in load_extension
    if self._call_load_ipython_extension(mod):
       │    │                            └ <module 'jupyter_ascending' from '/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/jupyter_ascendi...
       │    └ <function ExtensionManager._call_load_ipython_extension at 0x7f5167afed40>
       └ <IPython.core.extensions.ExtensionManager object at 0x7f51611ecc90>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/IPython/core/extensions.py", line 134, in _call_load_ipython_extension
    mod.load_ipython_extension(self.shell)
    │   │                      │    └ <traitlets.traitlets.Instance object at 0x7f5167afd990>
    │   │                      └ <IPython.core.extensions.ExtensionManager object at 0x7f51611ecc90>
    │   └ <function load_ipython_extension at 0x7f514ba7cdd0>
    └ <module 'jupyter_ascending' from '/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/jupyter_ascendi...
> File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/jupyter_ascending/extension.py", line 26, in load_ipython_extension
    jupyter_notebook.start_notebook_server_in_thread(notebook_name, jupyter_server)
    │                │                               │              └ <module 'jupyter_ascending.handlers.jupyter_server' from '/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-...
    │                │                               └ '/home/stuart/code/learn/jupyter/test.synced.ipynb'
    │                └ <function start_notebook_server_in_thread at 0x7f514bb69710>
    └ <module 'jupyter_ascending.handlers.jupyter_notebook' from '/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/sit...
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/jupyter_ascending/handlers/jupyter_notebook.py", line 81, in start_notebook_server_in_thread
    port_number=notebook_server_port,
                └ 39513
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/jsonrpcclient/__init__.py", line 8, in request
    return HTTPClient(endpoint).request(*args, **kwargs)
           │          │                  │       └ {'notebook_path': '/home/stuart/code/learn/jupyter/test.synced.ipynb', 'port_number': 39513}
           │          │                  └ ('register_notebook_server',)
           │          └ 'http://localhost:12517'
           └ <class 'jsonrpcclient.clients.http_client.HTTPClient'>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/apply_defaults/decorators.py", line 13, in wrapper
    return function(self, *args, **kwargs)
           │        │      │       └ {'notebook_path': '/home/stuart/code/learn/jupyter/test.synced.ipynb', 'port_number': 39513, 'trim_log_values': False, 'valid...
           │        │      └ ('register_notebook_server',)
           │        └ <jsonrpcclient.clients.http_client.HTTPClient object at 0x7f5160160390>
           └ <function Client.request at 0x7f514afc7b00>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/jsonrpcclient/client.py", line 232, in request
    validate_against_schema=validate_against_schema,
                            └ True
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/apply_defaults/decorators.py", line 13, in wrapper
    return function(self, *args, **kwargs)
           │        │      │       └ {'trim_log_values': False, 'validate_against_schema': True}
           │        │      └ ({'jsonrpc': '2.0', 'method': 'register_notebook_server', 'params': {'notebook_path': '/home/stuart/code/learn/jupyter/test.s...
           │        └ <jsonrpcclient.clients.http_client.HTTPClient object at 0x7f5160160390>
           └ <function Client.send at 0x7f514afc78c0>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/jsonrpcclient/client.py", line 171, in send
    self.validate_response(response)
    │    │                 └ <Response[0]>
    │    └ <function HTTPClient.validate_response at 0x7f514ba01a70>
    └ <jsonrpcclient.clients.http_client.HTTPClient object at 0x7f5160160390>
  File "/home/stuart/.pyenv/versions/3.7.8/envs/jupyter/lib/python3.7/site-packages/jsonrpcclient/clients/http_client.py", line 48, in validate_response
    raise ReceivedNon2xxResponseError(response.raw.status_code)
          │                           │        │   └ 403
          │                           │        └ <Response [403]>
          │                           └ <Response[0]>
          └ <class 'jsonrpcclient.exceptions.ReceivedNon2xxResponseError'>

jsonrpcclient.exceptions.ReceivedNon2xxResponseError: Received 403 status code
```

`pip list`

```shell
Package             Version
------------------- -----------
apply-defaults      0.1.4
argon2-cffi         20.1.0
async-generator     1.10
attrs               19.3.0
backcall            0.2.0
bleach              3.2.1
certifi             2020.6.20
cffi                1.14.3
chardet             3.0.4
click               7.1.2
decorator           4.4.2
defusedxml          0.6.0
edlib               1.3.8.post1
entrypoints         0.3
idna                2.10
importlib-metadata  2.0.0
ipykernel           5.3.4
ipython             7.18.1
ipython-genutils    0.2.0
ipywidgets          7.5.1
jedi                0.17.2
Jinja2              2.11.2
jsonrpcclient       3.3.6
jsonrpcserver       4.1.3
jsonschema          3.2.0
jupyter             1.0.0
jupyter-ascending   0.1.6
jupyter-client      6.1.7
jupyter-console     6.2.0
jupyter-core        4.6.3
jupyterlab-pygments 0.1.2
jupytext            1.6.0
loguru              0.4.1
markdown-it-py      0.5.5
MarkupSafe          1.1.1
mistune             0.8.4
nbclient            0.5.0
nbconvert           6.0.7
nbformat            5.0.7
nest-asyncio        1.4.1
notebook            6.1.4
packaging           20.4
pandocfilters       1.4.2
parso               0.7.1
pexpect             4.8.0
pickleshare         0.7.5
pip                 20.1.1
prometheus-client   0.8.0
prompt-toolkit      3.0.7
ptyprocess          0.6.0
pycparser           2.20
Pygments            2.7.1
pyparsing           2.4.7
pyrsistent          0.17.3
python-dateutil     2.8.1
PyYAML              5.3.1
pyzmq               19.0.2
qtconsole           4.7.7
QtPy                1.9.0
requests            2.24.0
Send2Trash          1.5.0
setuptools          47.1.0
six                 1.15.0
terminado           0.9.1
testpath            0.4.4
toml                0.10.1
tornado             6.0.4
traitlets           5.0.4
urllib3             1.25.10
wcwidth             0.2.5
webencodings        0.5.1
widgetsnbextension  3.5.1
zipp                3.3.0
```

jupyter terminal shows the following once my `test.synced.ipynb` file is opened in the browser.

```shell
[I 14:49:46.695 NotebookApp] [Jupytext Server Extension] Deriving a JupytextContentsManager from LargeFileManager
[I 14:49:46.698 NotebookApp] Serving notebooks from local directory: /home/stuart/code/learn/jupyter
[I 14:49:46.698 NotebookApp] Jupyter Notebook 6.1.4 is running at:
[I 14:49:46.698 NotebookApp] http://localhost:12517/?token=537f160948d189a08504813789ea6b765ad1f92dd0a7f62b
[I 14:49:46.698 NotebookApp]  or http://127.0.0.1:12517/?token=537f160948d189a08504813789ea6b765ad1f92dd0a7f62b
[I 14:49:46.699 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:49:46.819 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///home/stuart/.local/share/jupyter/runtime/nbserver-1020902-open.html
    Or copy and paste one of these URLs:
        http://localhost:12517/?token=537f160948d189a08504813789ea6b765ad1f92dd0a7f62b
     or http://127.0.0.1:12517/?token=537f160948d189a08504813789ea6b765ad1f92dd0a7f62b
Opening in existing browser session.
[I 14:49:54.869 NotebookApp] Kernel started: f6a0ba75-ab1f-41d6-9bfa-0c9121977f94, name: python3
[W 14:49:56.046 NotebookApp] 403 POST / (::1): '_xsrf' argument missing from POST
[W 14:49:56.047 NotebookApp] 403 POST / (::1) 0.87ms referer=None
```

**Comment by tjdevries** [comment]
@McCroden Why were you running it w/ the port set to that number?

That's the number that the internal http server expects to run on (which is why it's crashing I think).

**Comment by tjdevries** [comment]
We fixed this :)
