### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: during Installation

### ISSUE THREAD

**Issue by IliaOzhmegov** [untitled-ai/jupyter_ascending#39]
When running
```
$ pip install jupyter_ascending && \
jupyter nbextension    install jupyter_ascending --sys-prefix --py && \
jupyter nbextension     enable jupyter_ascending --sys-prefix --py && \
jupyter serverextension enable jupyter_ascending --sys-prefix --py
```

The output ends with a permission error:
```
Installing /Users/iliaozhmegov/Library/Python/3.8/lib/python/site-packages/jupyter_ascending/nbextension/static -> jupyter_ascending
Traceback (most recent call last):
  File "/Users/iliaozhmegov/Library/Python/3.8/bin/jupyter-nbextension", line 8, in <module>
    sys.exit(main())
  File "/Users/iliaozhmegov/Library/Python/3.8/lib/python/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/iliaozhmegov/Library/Python/3.8/lib/python/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/Users/iliaozhmegov/Library/Python/3.8/lib/python/site-packages/notebook/nbextensions.py", line 980, in start
    super().start()
  File "/Users/iliaozhmegov/Library/Python/3.8/lib/python/site-packages/jupyter_core/application.py", line 253, in start
    self.subapp.start()
  File "/Users/iliaozhmegov/Library/Python/3.8/lib/python/site-packages/notebook/nbextensions.py", line 708, in start
    self.install_extensions()
  File "/Users/iliaozhmegov/Library/Python/3.8/lib/python/site-packages/notebook/nbextensions.py", line 679, in install_extensions
    full_dests = install(self.extra_args[0],
  File "/Users/iliaozhmegov/Library/Python/3.8/lib/python/site-packages/notebook/nbextensions.py", line 214, in install_nbextension_python
    full_dest = install_nbextension(
  File "/Users/iliaozhmegov/Library/Python/3.8/lib/python/site-packages/notebook/nbextensions.py", line 118, in install_nbextension
    ensure_dir_exists(nbext)
  File "/Users/iliaozhmegov/Library/Python/3.8/lib/python/site-packages/jupyter_core/utils/__init__.py", line 11, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/share/jupyter'
```

I believe it may be related with M1.

**Comment by IliaOzhmegov** [comment]
I had to run Installment in the following way:

```
python3 -m pip install jupyter_ascending 
sudo jupyter nbextension    install jupyter_ascending --sys-prefix --py 
sudo jupyter nbextension     enable jupyter_ascending --sys-prefix --py 
sudo jupyter serverextension enable jupyter_ascending --sys-prefix --py
```
