### ISSUE TITLE
setup broken in python 3.10

### ISSUE THREAD

**Issue by qubidt** [untitled-ai/jupyter_ascending#42]
this check in `setup.py`:

https://github.com/untitled-ai/jupyter_ascending/blob/ab7ecec2654872726be1ebfa94900dc6745a7224/setup.py#L23

fails:

```
Traceback (most recent call last):
  File "jupyter_ascending/setup.py", line 23, in <module>
    ensure_python(">=3.4")
  File "jupyter_ascending/setupbase.py", line 104, in ensure_python
    raise ValueError('Python version %s unsupported' % part)
ValueError: Python version 3.10 unsupported
```

because `ensure_python` does not behave as expected when the python version >= 3.10:

https://github.com/untitled-ai/jupyter_ascending/blob/ab7ecec2654872726be1ebfa94900dc6745a7224/setupbase.py#L89-L104

not sure why [`python_requires`](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#python-requires) isn't just used instead, but if `ensure_python`'s behavior is required, it can be fixed by:

```diff
diff --git a/setupbase.py b/setupbase.py
index b0792ea..bbfed7a 100644
--- a/setupbase.py
+++ b/setupbase.py
@@ -34,6 +34,8 @@ from distutils import log
 from setuptools.command.develop import develop
 from setuptools.command.bdist_egg import bdist_egg
 
+from packaging.specifiers import Specifier
+
 try:
     from wheel.bdist_wheel import bdist_wheel
 except ImportError:
@@ -92,15 +94,10 @@ def ensure_python(specs):
     if not isinstance(specs, (list, tuple)):
         specs = [specs]
     v = sys.version_info
-    part = '%s.%s' % (v.major, v.minor)
+    part = f"{v.major}.{v.minor}.{v.micro}"
     for spec in specs:
-        if part == spec:
+        if Specifier(spec).contains(part):
             return
-        try:
-            if eval(part + spec):
-                return
-        except SyntaxError:
-            pass
     raise ValueError('Python version %s unsupported' % part)
```

(`packaging` is required by setuptools so it's already available)

**Comment by zplizzi** [comment]
This should hopefully be fixed by #46! Let me know if you're still having trouble.
