### ISSUE TITLE
Can't sync in Python 3.10

### ISSUE THREAD

**Issue by IliaOzhmegov** [untitled-ai/jupyter_ascending#43]
I built a simple `Dockerfile`:
```
FROM python:3.10.8

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt
```
[requirements.txt](https://github.com/untitled-ai/jupyter_ascending/files/9782325/requirements.txt)

and then
launch jupyter notebook with the command:
```
docker run --name jptr-asc-cont -p 8888:8888 --rm -it test-jptr-asc jupyter notebook --no-browser --allow-root --ip 0.0.0.0
```

However, after successful installation in docker container: 
```
pip install jupyter_ascending && \
    jupyter nbextension    install jupyter_ascending --sys-prefix --py && \
    jupyter nbextension     enable jupyter_ascending --sys-prefix --py && \
    jupyter serverextension enable jupyter_ascending --sys-prefix --py
```
From docker container **Quickstart** fails at 4th step:
```
python -m jupyter_ascending.requests.sync --filename example.sync.py
```

With the issue:
```
root@9157f020cf89:/usr/src/app# python -m jupyter_ascending.requests.sync --filename example.sync.py
Logging Jupyter Ascending logs to /tmp/jupyter_ascending/log.log
2022-10-14T03:46:35.071256+0000 - An error has been caught in function '<module>', process 'MainProcess' (64), thread 'MainThread' (281473422687536):
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/jupyter_ascending/requests/client_lib.py", line 24, in request_notebook_command
    result = request(
             └ <function request at 0xffffa1927f40>
  File "/usr/local/lib/python3.10/site-packages/jsonrpcclient/__init__.py", line 8, in request
    return HTTPClient(endpoint).request(*args, **kwargs)
           │          │                  │       └ {'command_name': 'SyncRequest', 'notebook_path': '/usr/src/app/example.sync.py', 'data': {'file_name': '/usr/src/app/example....
           │          │                  └ ('perform_notebook_request',)
           │          └ 'http://localhost:8888/jupyter_ascending'
           └ <class 'jsonrpcclient.clients.http_client.HTTPClient'>
  File "/usr/local/lib/python3.10/site-packages/apply_defaults/decorators.py", line 13, in wrapper
    return function(self, *args, **kwargs)
           │        │      │       └ {'command_name': 'SyncRequest', 'notebook_path': '/usr/src/app/example.sync.py', 'data': {'file_name': '/usr/src/app/example....
           │        │      └ ('perform_notebook_request',)
           │        └ <jsonrpcclient.clients.http_client.HTTPClient object at 0xffff9f0d1960>
           └ <function Client.request at 0xffffa18293f0>
  File "/usr/local/lib/python3.10/site-packages/jsonrpcclient/client.py", line 229, in request
    return self.send(
           │    └ <function Client.send at 0xffffa18291b0>
           └ <jsonrpcclient.clients.http_client.HTTPClient object at 0xffff9f0d1960>
  File "/usr/local/lib/python3.10/site-packages/apply_defaults/decorators.py", line 13, in wrapper
    return function(self, *args, **kwargs)
           │        │      │       └ {'trim_log_values': False, 'validate_against_schema': True}
           │        │      └ ({'jsonrpc': '2.0', 'method': 'perform_notebook_request', 'params': {'command_name': 'SyncRequest', 'notebook_path': '/usr/sr...
           │        └ <jsonrpcclient.clients.http_client.HTTPClient object at 0xffff9f0d1960>
           └ <function Client.send at 0xffffa1829120>
  File "/usr/local/lib/python3.10/site-packages/jsonrpcclient/client.py", line 171, in send
    self.validate_response(response)
    │    │                 └ <Response[0]>
    │    └ <function HTTPClient.validate_response at 0xffff9f0e5ab0>
    └ <jsonrpcclient.clients.http_client.HTTPClient object at 0xffff9f0d1960>
  File "/usr/local/lib/python3.10/site-packages/jsonrpcclient/clients/http_client.py", line 48, in validate_response
    raise ReceivedNon2xxResponseError(response.raw.status_code)
          │                           │        │   └ 403
          │                           │        └ <Response [403]>
          │                           └ <Response[0]>
          └ <class 'jsonrpcclient.exceptions.ReceivedNon2xxResponseError'>

jsonrpcclient.exceptions.ReceivedNon2xxResponseError: Received 403 status code


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'jupyter_ascending.requests', '__loader__': <_frozen_importlib_exter...
           │         └ <code object <module> at 0xffff9f39c2f0, file "/usr/local/lib/python3.10/site-packages/jupyter_ascending/requests/sync.py", l...
           └ <function _run_code at 0xffffa2c59000>
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'jupyter_ascending.requests', '__loader__': <_frozen_importlib_exter...
         └ <code object <module> at 0xffff9f39c2f0, file "/usr/local/lib/python3.10/site-packages/jupyter_ascending/requests/sync.py", l...
> File "/usr/local/lib/python3.10/site-packages/jupyter_ascending/requests/sync.py", line 36, in <module>
    send(arguments.filename)
    │    │         └ 'example.sync.py'
    │    └ Namespace(filename='example.sync.py')
    └ <function send at 0xffff9f3a05e0>
  File "/usr/local/lib/python3.10/site-packages/jupyter_ascending/requests/sync.py", line 24, in send
    request_notebook_command(request_obj)
    │                        └ SyncRequest(file_name='/usr/src/app/example.sync.py', contents='# ---\n# jupyter:\n#   jupytext:\n#     text_representation:\...
    └ <function request_notebook_command at 0xffff9f3a0550>
  File "/usr/local/lib/python3.10/site-packages/jupyter_ascending/requests/client_lib.py", line 43, in request_notebook_command
    raise RequestFailure(
          └ <class 'jupyter_ascending.requests.client_lib.RequestFailure'>

jupyter_ascending.requests.client_lib.RequestFailure: Unable to process request. Is jupyter-ascending installed in the server's python environment? Perhaps something else is running on this port? Received 403 status code
root@9157f020cf89:/usr/src/app#
─────────────────────────────────
```

#42 might be related

**Comment by leoenix** [comment]
Same issue here.

**Comment by zplizzi** [comment]
Can you try this again with the new version `0.1.24`?

**Comment by IliaOzhmegov** [comment]
Hi @zplizzi I tried to do it in the following way, like natively on my system, which is sadly known **Apple M1 Pro** and it worked out. I'm not sure but I think that the problem was that I was trying to launch it in the docker container. In the code below I successfully launch it in the virtual environment. But I believe I did not correct command to launch specific environment, which is okay because I manually switched it in the notebook.
```
#!/bin/bash
FOLDER=ascending

mkdir $FOLDER 
cd $FOLDER


python3.10 -m venv .venv
source .venv/bin/activate
pip install --upgrade pip
pip install jupyter 

python -m ipykernel install --user --name myenv --display-name "Python3.10 (test ascending)"
pip install jupyter_ascending && \
	python -m jupyter nbextension    install jupyter_ascending --sys-prefix --py && \
	python -m jupyter nbextension     enable jupyter_ascending --sys-prefix --py && \
	python -m jupyter serverextension enable jupyter_ascending --sys-prefix --py


python -m jupyter_ascending.scripts.make_pair --base example
python -m jupyter notebook --name="Python3.10 (test ascending)" example.sync.ipynb
# BUT STILL HAD TO manually to switch kernel to testing one named='Python3.10 (test ascending)'

# in another panel/console/terminal and etc but in the same folder $FOLDER
echo 'print("Hello World!")' >> example.sync.py
source .venv/bin/activate
python -m jupyter_ascending.requests.sync --filename example.sync.py
python -m jupyter_ascending.requests.execute --filename example.sync.py --line 16
```

**Comment by IliaOzhmegov** [comment]
I guess since it works fine now, I might confidently close the issue. However, I would like to highlight that the current version is not  tagged as `0.1.24`. There is still the previous tag `0.1.23`.

**Comment by zplizzi** [comment]
Good catch, fixed now!
