### ISSUE TITLE
pip cannot install jupyter ascending

### ISSUE THREAD

**Issue by ochalkley-advai** [untitled-ai/jupyter_ascending#64]
```
$ pip install jupyter_ascending
Collecting jupyter_ascending
  Using cached jupyter_ascending-0.1.27-py3-none-any.whl.metadata (743 bytes)
Collecting aiohttp<4.0.0,>=3.8.4 (from jupyter_ascending)
  Using cached aiohttp-3.9.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.5 kB)
Collecting editdistance<0.7.0,>=0.6.2 (from jupyter_ascending)
  Using cached editdistance-0.6.2.tar.gz (31 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "/home/oli/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/oli/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/oli/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ocdndz0u/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ocdndz0u/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ocdndz0u/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 25, in <module>
        File "/tmp/pip-build-env-ocdndz0u/overlay/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1010, in cythonize
          module_list, module_metadata = create_extension_list(
                                         ^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ocdndz0u/overlay/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 845, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/tmp/pip-build-env-ocdndz0u/overlay/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 117, in nonempty
          raise ValueError(error_msg)
      ValueError: 'editdistance/bycython.pyx' doesn't match any files
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by tunaflsh** [comment]
I'm getting the same error. Are there any solutions?

**Comment by p100mma** [comment]
I had the same problem trying to install it on remote CentOS 7. 
What helped was following the instructions regarding the 'editdistance' dependency mentioned in the thread below:
https://stackoverflow.com/questions/77484622/valueerror-editdistance-bycython-pyx-doesnt-match-any-files-when-downloading

I needed to download the specific version of the dependency from github, as opposed to the latest from PyPI

`pip install git+https://github.com/roy-ht/editdistance.git@v0.6`

**Comment by losnappas** [comment]
PR accepted? I'd update the version of editdistance, it breaks pip currently. Have to override with the git version 0.6.2, newest editdistance is 0.8.x

**Comment by meditans** [comment]
I'm installing `jupyter_ascending` via `uv` and in order to make it work I had to pin the python interpreter to 3.11. So:
```
uv init example -p 3.11
cd example
uv add jupyter_ascending
```
This works because, as you can see on `editdistance` on github, there's a wheel for 3.11 but not for 3.12

**Comment by isidroas** [comment]
This works for me:

```
pip install jupyter_ascending editdistance==0.8.1
```

It installs the latest version instead of 'editdistance<0.7.0,>=0.6.2'
