### ISSUE TITLE
Unabled to find File?

### ISSUE THREAD

**Issue by mova** [untitled-ai/jupyter_ascending#9]
Hi there!
After setting up jupyter_ascending, I'm getting an error message and I don't know what to make of it.

File Content
```# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: light
#       format_version: '1.5'
#       jupytext_version: 1.7.1
#   kernelspec:
#     display_name: Python 3
#     language: python
#     name: python3
# ---

print('foo')
```

Error Message in Jupyter

```
{"jsonrpc": "2.0", "method": "perform_notebook_request", "params": {"command_name": "SyncRequest", "notebook_path": "/home/user/projects/dictateMeBot/test.synced.py", "data": {"file_name": "/home/user/projects/dictateMeBot/test.synced.py", "contents": "# ---\n# jupyter:\n#  jupytext:\n#   text_representation:\n#    extension: .py\n#    format_name: light\n#    format_version: '1.5'\n#    jupytext_version: 1.7.1\n#  kernelspec:\n#   display_name: Python 3\n#   language: python\n#   name: python3\n# ---\n\nprint('foo')\n\n"}}, "id": 1}
2020-12-02T10:53:28.449440+0100 - Unabled to find /home/user/projects/dictateMeBot/test.synced.py in {}
{"jsonrpc": "2.0", "result": {"success": false, "notebook_path": "/home/user/projects/dictateMeBot/test.synced.py"}, "id": 1}
```

Error Message in Vim

```
2020-12-02 10:53:28.441 | INFO     | __main__:send:16 - Syncing File: /home/user/projects/dictateMeBot/test.synced.py...
2020-12-02 10:53:28.448 | INFO     | jupyter_ascending.handlers:do_POST:49 - JupyterServer processing request:
                {"jsonrpc": "2.0", "method": "perform_notebook_request", "params": {"command_name": "SyncRequest", "notebook_path": "/home/user/projects/dictateMeBot/test.synced.py", "data": {"file_name": "/home/user/projects/dictateMeBot/test.synced.py", "contents": "# ---\n# jupyter:\n#   jupytext:\n#     text_representation:\n#       extension: .py\n#       format_name: light\n#       format_version: '1.5'\n#       jupytext_version: 1.7.1\n#   kernelspec:\n#     display_name: Python 3\n#     language: python\n#     name: python3\n# ---\n\nprint('foo')\n\n"}}, "id": 1}
2020-12-02 10:53:28.449 | WARNING  | jupyter_ascending.handlers.jupyter_server:perform_notebook_request:54 - Unabled to find /home/user/projects/dictateMeBot/test.synced.py in {}
2020-12-02 10:53:28.449 | INFO     | jupyter_ascending.handlers:do_POST:53 - Got Response:
                {"jsonrpc": "2.0", "result": {"success": false, "notebook_path": "/home/user/projects/dictateMeBot/test.synced.py"}, "id": 1}
2020-12-02 10:53:28.450 | ERROR    | __main__:<module>:43 - An error has been caught in function '<module>', process 'MainProcess' (63346), thread 'MainThread' (139936503093056):
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'jupyter_ascending.requests', '__loader__': <_frozen_importlib_exter...
           │         └ <code object <module> at 0x7f457f4f59d0, file "/home/user/.local/pylibs-PopOS20/lib/python3.8/site-packages/jupyter_ascendi...
           └ <function _run_code at 0x7f458086b3a0>
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'jupyter_ascending.requests', '__loader__': <_frozen_importlib_exter...
         └ <code object <module> at 0x7f457f4f59d0, file "/home/user/.local/pylibs-PopOS20/lib/python3.8/site-packages/jupyter_ascendi...
> File "/home/user/.local/pylibs-PopOS20/lib/python3.8/site-packages/jupyter_ascending/requests/sync.py", line 43, in <module>
    send(arguments.filename)
    │    │         └ '/home/user/projects/dictateMeBot/test.synced.py'
    │    └ Namespace(filename='/home/user/projects/dictateMeBot/test.synced.py')
    └ <function send at 0x7f458078f790>
  File "/home/user/.local/pylibs-PopOS20/lib/python3.8/site-packages/jupyter_ascending/requests/sync.py", line 32, in send
    jupyter_server.request_notebook_command(request_obj)
    │              │                        └ SyncRequest(file_name='/home/user/projects/dictateMeBot/test.synced.py', contents="# ---\n# jupyter:\n#   jupytext:\n#     ...
    │              └ <function request_notebook_command at 0x7f457f4f61f0>
    └ <module 'jupyter_ascending.handlers.jupyter_server' from '/home/user/.local/pylibs-PopOS20/lib/python3.8/site-packages/jupy...
  File "/home/user/.local/pylibs-PopOS20/lib/python3.8/site-packages/jupyter_ascending/handlers/jupyter_server.py", line 128, in request_notebook_command
    raise Exception(f"Failed to complete request. {result.data}")

Exception: Failed to complete request. {"jsonrpc": "2.0", "result": {"success": false, "notebook_path": "/home/user/projects/dictateMeBot/test.synced.py"}, "id": 1}
```

**Comment by tjdevries** [comment]
Do you have a `.synced.ipynb` file open in Jupyter notebook at the time?

Also, you may want to try and add a `# %%`  before your `print()` just in case.

**Comment by mova** [comment]
Hi, thanks for you answer, apparently this extension is not compatible with jupyter lab, it work in jupyter notebook.
I have another issue though. This code:
```
# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: light
#       format_version: '1.5'
#       jupytext_version: 1.7.1
#   kernelspec:
#     display_name: Python 3
#     language: python
#     name: python3
# ---

# %% [markdown]
#TEST

# %%
x='foo'

if True:
    pass
print('bar')

# %%
!ls
```
generates this Notebook.
![Screenshot from 2020-12-04 11-21-34](https://user-images.githubusercontent.com/779688/101152164-f872e780-3622-11eb-93c4-fd037badceab.png)
What is happening to the markdown?
Why is the cell split between the assignment of `x` and the if statement?
How do i get rid of the `# %%` in the notebook?

**Comment by g6ai** [comment]
@mova I have the very similar error message when I tried to use it in JupyterLab. Is it safe to assume the extension is not ready for JupyterLab?

**Comment by zplizzi** [comment]
I opened #24 to track the JupyterLab issue - so I'm going to go ahead and close this one. Feel free to open a new issue if y'all are still having trouble with anything!
